### ISSUE TITLE
actuator-exposure

### ISSUE THREAD

**Issue by ooMia** [Inssiders/BE-main-archive-1#37]
https://github.com/Inssiders/BE-main/tree/main/src/main/resources/application.yml#L22-L24
```yml
management:
  server:
    base-path: /actuator
```
제가 정확히 몰라서 그러는데 GET `/actuator/health` 요청에 문제 없나요?
